### PR TITLE
Add user

### PR DESCRIPTION
**Pull request by MitulKapoor**

### CODE REVIEW

**Comment by MitulKapoor** [comment]
Creating new feature - Add users dynamically via UI

**Comment by davidnewcomb** [comment]
Wow thanks, I'll take a look.

**Comment by davidnewcomb** [comment]
I like what you have done however there are a few changes I need.

**ListUserPage** - refactor the `Dialog` so it is in its own class (e.g. `c/AddUserDialog`). The changes to `ListUserPage` should be minimal (good practice). There may also be other places in the UI where this feature is useful. The `ListUserPage` has a refresh callback which can be called after adding the user.
Adding the feature inline has effectively shared the `state` object between the list users page and the dialog. This causes a lot of unnecessary updates on the user list as you type into the dialog boxes. Separating the states will get rid of this problem.

**Utils.addUser** - change order of parameters, biggest first (convention)

**Credentials** - make field variables `private`, and replace spaces for tabs.

**Comment by davidnewcomb** [comment]
I've added a commit to `master` that will let your branch code run in debug mode from a separate `yarn start`.

**Comment by MitulKapoor** [comment]
> I like what you have done however there are a few changes I need.
> 
### **ListUserPage** - refactor the `Dialog` so it is in its own class (e.g. `c/AddUserDialog`). The changes to `ListUserPage` should be minimal (good practice). There may also be other places in the UI where this feature is useful. The `ListUserPage` has a refresh callback which can be called after adding the user.
### Adding the feature inline has effectively shared the `state` object between the list users page and the dialog. This causes a lot of unnecessary updates on the user list as you type into the dialog boxes. Separating the states will get rid of this problem.**
_Agreed on keeping it in a difference class is a good practice. But opening and closing of dialog would be then managed via 2 classes (Parent class which calls the dialog, and dialog class). To avoid this situation this was added to the same class_
> 
### **Utils.addUser** - change order of parameters, biggest first (convention)
Could you please elaborate this?
### **Credentials** - make field variables `private`, and replace spaces for tabs.
Updated

**Comment by davidnewcomb** [comment]
**ListUserPage**
The parent call doesn't "call" the dialog, it defines it. I was thinking something like:

In `ListUserPage`:

```
return (
    <div>
        <PageHeader title="All Users"/>
        <Paper>
            <AddUserDialog reload={this.reload}/>
            <table>
                ...
            </table>
        </Page>
    </div>
)
```
`handlerOpen/Close/Change`, `addUser` and their `state` can live in `AddUserDialog`.
You can add an error box to the dialog to display any errors from adding the user.
When you have finished, the `handleClose` calls `this.props.reload()` (or not).
```
class AddUserDialog extends Component {
    constructor(props) {
        super(props)

    addUser = () => {
        let url = AddUserUrl()
        axios.post(url,{
                login: this.state.login,
                email: this.state.email,
                password: this.state.password
        }).then( res => {
            this.props.reload()
```
There's no need to share `state`. We are just passing in a reference to a function as a parameter. Still learning about material-ui but I think it's possible to set that up.

**Utils.addUser**
There is a bit of debate around argument order, but I've always gone for significant object first i.e. (context, manager, class/object, param1). It this case it looks like a "named sender" call where the first parameter is the object and the second is the thing the object needs (object, param). There may be more parameters in the future so the natural change would be (object, param1, param2). There's other reasons like some languages let you not specify parameters at the end and it's nice to have a consistent style.

https://softwareengineering.stackexchange.com/questions/101346/what-is-best-practice-on-ordering-parameters-in-a-function

**Credentials**

Thanks!

**Comment by MitulKapoor** [comment]
Please review.
For AddUserDialog, the visibility will be controlled by calling class itself, as parent class will allow/hide whether it wants to show the dialog on top of it. Clicking outside the dialog box should also dismiss the dialog, which is happening in this case.

**Comment by davidnewcomb** [comment]
I thought the pop up box was model. Thanks for making the change. I'll take a look.

**Comment by davidnewcomb** [comment]
I have checked in a branch called `pull_10_add_user`. It is taken from your `add_user:HEAD`.
I have moved everything related to the dialog into the dialog class. Like I said above they can be completely separate. The parent does not need to know anything about the add user dialog.

`AddUserDialog` has 3 different implementations of how to handle it
1. Move *Add User* button to AddUserDialog (commented out)
1. Add *Add User* to `ListUserPage` and inject using `this.props.children` add `onClick` with wrapper `<div>` (commented out)
1. Add *Add User* to `ListUserPage` and inject using `this.props.children` and dynamically attach an `onClick` to the only element.

The `state` is no longer shared and the `ListUserPage`, it doesn't update as you type in the dialog.
Clicking outside the box closes the pop up automatically, parent doesn't need to care.
When there is a network failure an error message is generated and displayed in the open dialog which remains open.

It needs tidying up and the error message could do with a bit of styling but hopefully you can see what I'm getting at. Use any of my code to update your branch. Please move all the add user stuff into the `AddUserDialog`.

**Comment by MitulKapoor** [comment]
> I have checked in a branch called `pull_10_add_user`. It is taken from your `add_user:HEAD`.
> I have moved everything related to the dialog into the dialog class. Like I said above they can be completely separate. The parent does not need to know anything about the add user dialog.
> 
> `AddUserDialog` has 3 different implementations of how to handle it
> 
> 1. Move _Add User_ button to AddUserDialog (commented out)
> 2. Add _Add User_ to `ListUserPage` and inject using `this.props.children` add `onClick` with wrapper `<div>` (commented out)
> 3. Add _Add User_ to `ListUserPage` and inject using `this.props.children` and dynamically attach an `onClick` to the only element.
> 
> The `state` is no longer shared and the `ListUserPage`, it doesn't update as you type in the dialog.
> Clicking outside the box closes the pop up automatically, parent doesn't need to care.
> When there is a network failure an error message is generated and displayed in the open dialog which remains open.
> 
> It needs tidying up and the error message could do with a bit of styling but hopefully you can see what I'm getting at. Use any of my code to update your branch. Please move all the add user stuff into the `AddUserDialog`.

**Comment by davidnewcomb** [comment]
Continued on #11

**Pull request closed without merging**
