### PR TITLE
ui update - adding material ui components

### PR DESCRIPTION
**Pull request by MitulKapoor**

### CODE REVIEW

**Comment by MitulKapoor** [comment]
Hello,
I wish to contribute to your work. I have made little changes to UI to add material UI components. Would like to contribute more to backend changes.
Request you to please review the pull request.

Regards,
Mitul Kapoor

**Comment by davidnewcomb** [comment]
Thanks, I'll take a look.

**Comment by davidnewcomb** [comment]
I've had a look and I like what you have done. There are several issues though, so I'd like you to fix them, before we can proceed.

General problems
1. `package.json` is missing `@material-ui/core`
1. You have removed all the `Octicon` so you can remove the `@primer/octicons-react` dependency.
1. In `ServerConfigRow`, can you change the `Card` width to 100%
1. In `ServerConfigPage` what does the onChange do? If you take it out there is no change!
1. Following error appears in the console log:
```
Warning: Failed prop type: The prop `children` is not supported. Please remove it.
    in ForwardRef(Tab) (created by WithStyles(ForwardRef(Tab)))
    in WithStyles(ForwardRef(Tab)) (at ViewMessagePage.js:144)
    in div (created by ForwardRef(Tabs))
    in div (created by ForwardRef(Tabs))
    in div (created by ForwardRef(Tabs))
    in ForwardRef(Tabs) (created by WithStyles(ForwardRef(Tabs)))
    in WithStyles(ForwardRef(Tabs)) (at ViewMessagePage.js:139)
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (at ViewMessagePage.js:138)
    in div (at ViewMessagePage.js:136)
    in ViewMessagePage (created by Context.Consumer)
    in Route (at App.js:57)
    in Switch (at App.js:35)
    in div (created by Container)
    in Container (at App.js:31)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:30)
    in BreadcrumbContextProvider (at App.js:29)
    in App (at src/index.js:10)
    in StrictMode (at src/index.js:9)
```
There are several other error messages like this where you are missing keys.
```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `ServerConfigPage`. See https://fb.me/react-warning-keys for more information.
    in WithStyles(ForwardRef(ExpansionPanel)) (at ServerConfigPage.js:49)
    in ServerConfigPage (at App.js:40)
    in Route (at App.js:39)
    in Switch (at App.js:35)
    in div (created by Container)
    in Container (at App.js:31)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:30)
    in BreadcrumbContextProvider (at App.js:29)
    in App (at src/index.js:10)
    in StrictMode (at src/index.js:9)
```
**Pro Tip - use the same style as the code you are editing** 
1. Please remove all the semi-colons (;) at the end of all your lines.
1. Please make sure that `import` statements are consistent and use single quotes (').
1. Please use consistent formatting `getHeaderDetails = () =>{` should be `getHeaderDetails = () => {`
1. When using `setState` put each variable on a separate line set examples in the code.
1. Please use consistent spacing `return (value == 0)?this.getMessageDetails():this.getHeaderDetails();`. Are you in a hurry? This does not help readability.

**Comment by MitulKapoor** [comment]
@davidnewcomb I have made suggested changes. Please review

**Comment by davidnewcomb** [comment]
Thanks, I'm getting to it!

**Comment by davidnewcomb** [comment]
Great work, thanks for making the changes.

**Pull request merged**
